hostAliases:
  - ip: 127.0.0.1
    hostnames:
      - status.localhost
prestashopSkipInstall: false
prestashopHost: vmware-prestashop.my
prestashopUsername: bitnamiTest
prestashopEmail: bitnamiTest@example.com
prestashopPassword: ComplicatedPassword123!4
prestashopCookieCheckIP: "no"
containerPorts:
  http: 8081
  https: 8444
podSecurityContext:
  enabled: true
  fsGroup: 1002
containerSecurityContext:
  enabled: true
  runAsUser: 1002
service:
  type: LoadBalancer
  ports:
    http: 80
mariadb:
  enabled: true
  auth:
    database: bitnami_test_prestashop
    username: bn_test_prestashop
    password: bitnami_test_prestashop