mediawikiHost: vmware-mediawiki.my
mediawikiUser: test_user
mediawikiPassword: ComplicatedPassword123!4
persistence:
  enabled: true
hostAliases:
  - ip: 127.0.0.1
    hostnames:
      - status.testhost
containerSecurityContext:
  enabled: true
  runAsUser: 1002
podSecurityContext:
  fsGroup: 1002
  enabled: true
service:
  type: LoadBalancer
  ports:
    http: 80
    https: 444
mariadb:
  enabled: true
  auth:
    database: test_db_database
    username: test_db_user
    password: test_db_password
