hostCNIBinDir: /home/kubernetes/bin
CNIMountPath: /bitnami/multus-cni/host
serviceAccount:
  create: true
  automountServiceAccountToken: true
containerSecurityContext:
  enabled: true
  runAsUser: 0
rbac:
  create: true
