# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: CMS
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.5-debian-11-r4
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r95
    - name: osclass
      image: docker.io/bitnami/osclass:8.2.0-debian-11-r3
apiVersion: v2
appVersion: 8.2.0
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - osclass-database
  version: 15.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Osclass allows you to easily create a classifieds site without any technical knowledge. It provides support for presenting general ads or specialized ads, is customizable, extensible and multilingual.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/osclass/img/osclass-stack-220x234.png
keywords:
- osclass
- classifieds
- http
- web
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: osclass
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/osclass
version: 18.2.2
