wordpressUsername: test_user
wordpressPassword: ComplicatedPassword123!4
wordpressEmail: test_user_email@email.com
mariadb:
  auth:
    database: test_wordpress_database
    username: test_wordpress_username
    password: test_wordpress_password
podSecurityContext:
  enabled: true
  fsGroup: 1002
containerSecurityContext:
  enabled: true
  runAsUser: 1002
wordpressTablePrefix: wordpress_
service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443
containerPorts:
  http: 8081
  https: 8444
hostAliases:
  - ip: 127.0.0.1
    hostnames:
      - status.localhost