jwt:
  secret: abcdefghijklmnopqrstuvwxyz123456
  anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjc1NDAwNDAwLAogICAgImV4cCI6IDE4MzMxNjY4MDAKfQ.ztuiBzjaVoFHmoljUXWmnuDN6QU2WgJICeqwyzyZO88
  serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAic2VydmljZV9yb2xlIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NzU0MDA0MDAsCiAgICAiZXhwIjogMTgzMzE2NjgwMAp9.qNsmXzz4tG7eqJPh1Y58DbtIlJBauwpqx39UF-MwM8k

auth:
  service:
    ports:
      http: 2222
meta:
  service:
    ports:
      http: 2223
realtime:
  service:
    ports:
      http: 2224
rest:
  service:
    ports:
      http: 2225
storage:
  service:
    ports:
      http: 2226
studio:
  service:
    ports:
      http: 2227

kong:
  service:
    ports:
      proxyHttp: 80
  kong:
    extraVolumeMounts:
      - name: rendered-declarative-conf
        mountPath: /bitnami/kong/declarative-conf/
    extraEnvVars:
      - name: KONG_DECLARATIVE_CONFIG
        value: /bitnami/kong/declarative-conf/kong.yml
      - name: KONG_DNS_ORDER
        value: LAST,A,CNAME
      - name: KONG_PLUGINS
        value: request-transformer,cors,key-auth,acl
